### Passo 1 - Importar Arquivos e Bibliotecas

In [1]:
import pandas as pd  # Manipulação de dados com DataFrames.
import win32com.client as win32  # Automação de e-mails via Outlook.
import pathlib  # Manipulação de caminhos de arquivos.

# Tentativa de carregar as bases de dados, com tratamento de erros (try/except) para garantir a robustez.
try:
    base_emails = pd.read_excel(r'Bases de Dados\Emails.xlsx')  # Lê a base de e-mails (Excel).
    base_lojas = pd.read_csv(r'Bases de Dados\Lojas.csv', encoding='latin1', sep=';')  # Lê a base de lojas (CSV).
    base_vendas = pd.read_excel(r'Bases de Dados\Vendas.xlsx')  # Lê a base de vendas (Excel).
    print('arquivos carregados com sucesso!')
except Exception as e:
    print(f"Erro ao carregar arquivo: {e}")  # Mensagem de erro com detalhes do problema.

# Exibe as bases carregadas para validação visual.
display(base_emails) 
display(base_lojas)
display(base_vendas)

arquivos carregados com sucesso!

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonteste+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonteste+alice@gmail.com
2,Norte Shopping,Laura,pythonteste+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonteste+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonteste+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,pythonteste+sophia@gmail.com
6,Rio Mar Recife,Isabella,pythonteste+isabella@gmail.com
7,Salvador Shopping,Heloisa,pythonteste+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,pythonteste+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,pythonteste+julia@gmail.com
10,Ribeirão Shopping,Lorena,pythonteste+lorena@gmail.com
11,Shopping Morumbi,Livia,pythonteste+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,pythonteste+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,pythonteste+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,pythonteste+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,pythonteste+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,pythonteste+arthur@gmail.com
17,Shopping Recife,Heitor,pythonteste+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,pythonteste+bernardo@gmail.com
19,Shopping SP Market,Davi,pythonteste+davi@gmail.com
20,Shopping Eldorado,Theo,pythonteste+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,pythonteste+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,pythonteste+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,pythonteste+pedro@gmail.com
24,Shopping Barra,Benjamin,pythonteste+benjamin@gmail.com
25,Diretoria,Diretoria,pythonteste+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2024-01-01,1,Sapato Estampa,1,358,358
1,1,2024-01-01,1,Camiseta,2,180,360
2,1,2024-01-01,1,Sapato Xadrez,1,368,368
3,2,2024-01-02,3,Relógio,3,200,600
4,2,2024-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2024-12-26,17,Short Listrado,2,102,204
100995,69996,2024-12-26,17,Mochila,4,270,1080
100996,69996,2024-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2024-12-26,11,Camisa Listrado,1,108,108
100998,69997,2024-12-26,11,Short Linho,2,133,266

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [2]:
# Combina as bases 'base_vendas' e 'base_lojas' com base na coluna 'ID Loja', 
# adicionando as informações das lojas à base de vendas.
base_vendas = base_vendas.merge(base_lojas, on='ID Loja')

# Exibe a base de vendas atualizada para verificar a junção.
display(base_vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2024-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2024-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2024-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2024-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2024-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2024-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2024-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2024-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2024-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2024-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [3]:
# Cria um dicionário com uma tabela (DataFrame) para cada loja, 
# onde a chave é o nome da loja e o valor é o subconjunto dos dados de vendas para aquela loja.
dicionario_base_lojas = {}
for loja in base_lojas['Loja']:
    dicionario_base_lojas[loja] = base_vendas.loc[base_vendas['Loja'] == loja, :]

# Exibe os dados da loja 'Rio Mar Recife' do dicionário.
display(dicionario_base_lojas['Rio Mar Recife'])

# Determina a data mais recente da base de vendas para usar como indicador.
data_indicador = base_vendas['Data'].max()

# Exibe a data do indicador no formato dia/mês/ano.
print(f'{data_indicador.day}/{data_indicador.month}/{data_indicador.year}')

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
62,46,2024-01-02,7,Camisa,1,100,100,Rio Mar Recife
63,46,2024-01-02,7,Calça Liso,2,190,380,Rio Mar Recife
64,46,2024-01-02,7,Cinto,1,200,200,Rio Mar Recife
113,87,2024-01-02,7,Camisa Estampa,1,113,113,Rio Mar Recife
142,109,2024-01-02,7,Camisa Gola V Listrado,3,116,348,Rio Mar Recife
...,...,...,...,...,...,...,...,...
100858,69905,2024-12-25,7,Mochila Listrado,2,275,550,Rio Mar Recife
100859,69905,2024-12-25,7,Camisa Xadrez,3,105,315,Rio Mar Recife
100860,69905,2024-12-25,7,Tênis Liso,3,266,798,Rio Mar Recife
100929,69954,2024-12-25,7,Chinelo,3,60,180,Rio Mar Recife
100930,69954,2024-12-25,7,Casaco Listrado,3,269,807,Rio Mar Recife

26/12/2024

### Passo 3 - Salvar a planilha na pasta de backup

In [4]:
# Define o caminho da pasta onde os arquivos de backup serão armazenados.
caminho_backup = pathlib.Path(r'Backup Arquivos Lojas')

# Lista todos os arquivos e pastas dentro do diretório de backup.
arquivos_pasta_backup = caminho_backup.iterdir()

# Cria uma lista com os nomes dos arquivos (sem o caminho completo).
lista_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup]

# Para cada loja no dicionário de dados:
for loja in dicionario_base_lojas:
    # Se a pasta da loja não existir, cria uma nova pasta para ela.
    if loja not in lista_nomes_backup:
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()
    
    # Cria o nome do arquivo de backup com base na data do indicador e o nome da loja.
    nome_arquivo = f'{data_indicador.month}_{data_indicador.day}_{loja}.xlsx'
    
    # Define o local completo onde o arquivo será salvo.
    local_arquivo = caminho_backup / loja / nome_arquivo
    
    # Salva os dados da loja no arquivo Excel.
    dicionario_base_lojas[loja].to_excel(local_arquivo)

### Passo 4 - Definir metas

In [5]:
# Definindo as metas para o faturamento e quantidade de produtos.
# Essas metas são utilizadas para comparar os resultados diários e anuais.

# Meta de faturamento diário (valor em unidades monetárias, ex: R$).
meta_faturamento_dia = 1000

# Meta de faturamento anual (valor em unidades monetárias, ex: R$).
meta_faturamento_ano = 1650000

# Meta de quantidade de produtos vendidos por dia.
meta_qtdeprodutos_dia = 4

# Meta de quantidade de produtos vendidos no ano.
meta_qtdeprodutos_ano = 120

# Meta de ticket médio diário (valor médio por venda).
meta_ticketmedio_dia = 500

# Meta de ticket médio anual (valor médio por venda).
meta_ticketmedio_ano = 500

### Passo 5 - Calcular o indicador para cada loja  e Enviar por e-mail para o gerente

In [6]:
for loja in dicionario_base_lojas:
    vendas_loja = dicionario_base_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data']==data_indicador,:]
    
    # Somar apenas as colunas numéricas, excluindo a coluna 'Data'
    faturamento_ano = vendas_loja['Valor Final'].sum()  # Soma do faturamento do ano
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()  # Soma do faturamento do dia
    #print(faturamento_ano)
    #print(faturamento_dia)
    
    # Contar a quantidade de produtos únicos
    qtde_produtos_ano = len(vendas_loja['Produto'].unique())
    qtde_produtos_dia = len(vendas_loja_dia['Produto'].unique())
    #print(qtde_produtos_ano)
    #print(qtde_produtos_dia)
    
    # Agrupar por 'Código Venda' e somar apenas as colunas numéricas
    valor_venda_ano = vendas_loja.select_dtypes(include=['number']).groupby('Código Venda').sum()
    ticket_medio_ano = valor_venda_ano['Valor Final'].mean()
    #print(ticket_medio_ano)
    
    valor_venda_dia = vendas_loja_dia.select_dtypes(include=['number']).groupby('Código Venda').sum()
    ticket_medio_dia = valor_venda_dia['Valor Final'].mean()
    
    #print(ticket_medio_dia)
    #display(valor_venda_dia)
    # Exibe os dados das vendas do dia
    #display(vendas_loja_dia)

    #envio dos emails para cada gerente de loja
    outlook = win32.Dispatch('outlook.application')
    nome = base_emails.loc[base_emails['Loja']==loja,'Gerente'].values[0]

    mail = outlook.CreateItem(0)
    mail.To = base_emails.loc[base_emails['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {data_indicador.day}/{data_indicador.month} - Loja {loja}'
    #mail.Body = 'Texto do E-mail'
    
    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if qtde_produtos_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if qtde_produtos_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'

    mail.HTMLBody = f'''
    <p>Prezado(a), {nome}</p>

    <p>O resultado de ontem <strong>({data_indicador.day}/{data_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>

    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Dia</th>
        <th>Meta Dia</th>
        <th>Cenário Dia</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_dia:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_dia}</td>
        <td style="text-align: center">{meta_qtdeprodutos_dia}</td>
        <td style="text-align: center"><font color="{cor_qtde_dia}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_dia:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_dia}">◙</font></td>
      </tr>
    </table>
    <br>
    <table>
      <tr>
        <th>Indicador</th>
        <th>Valor Ano</th>
        <th>Meta Ano</th>
        <th>Cenário Ano</th>
      </tr>
      <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_ano:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{qtde_produtos_ano}</td>
        <td style="text-align: center">{meta_qtdeprodutos_ano}</td>
        <td style="text-align: center"><font color="{cor_qtde_ano}">◙</font></td>
      </tr>
      <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${ticket_medio_ano:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_ano}">◙</font></td>
      </tr>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>

    <p>Qualquer dúvida estou à disposição.</p>
    <p>Atenciosamente,</p>
    <p>Fernando Vale</p>
    '''

    # Anexos (pode colocar quantos quiser):
    attachment  = pathlib.Path.cwd() / caminho_backup / loja / f'{data_indicador.month}_{data_indicador.day}_{loja}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    print(f'E-mail da Loja {loja} enviado.')
    break

E-mail da Loja Iguatemi Esplanada enviado.

### Passo 6 - Criar ranking para diretoria

In [7]:
# versão corrigida
# Agrupar por loja e calcular o faturamento total
faturamento_lojas = base_vendas.groupby('Loja')['Valor Final'].sum()

# Ordenar por valor total em ordem decrescente
faturamento_lojas_ano = faturamento_lojas.sort_values(ascending=False)
# Converter a Series para um DataFrame
faturamento_lojas_ano = faturamento_lojas_ano.reset_index()

# Renomear as colunas para garantir clareza
faturamento_lojas_ano.columns = ['Loja', 'Valor Final']

# Exibir a tabela (mantendo a versão original para operações futuras)
faturamento_lojas_ano_styled = faturamento_lojas_ano.style.hide(axis='index')
display(faturamento_lojas_ano_styled)

# Exportar para Excel
nome_arquivo = f'{data_indicador.month}_{data_indicador.day}_Ranking Anual.xlsx'
faturamento_lojas_ano.to_excel(f'Backup Arquivos Lojas\{nome_arquivo}', index=False)

# Filtrar as vendas do dia específico
vendas_dia = base_vendas[base_vendas['Data'] == data_indicador]

# Agrupar por loja e calcular o faturamento total, convertendo para DataFrame
faturamento_lojas_dia = vendas_dia.groupby('Loja')['Valor Final'].sum().reset_index()

# Renomear as colunas para garantir clareza
faturamento_lojas_dia.columns = ['Loja', 'Valor Final']

# Ordenar por valor total em ordem decrescente
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False)

# Exibir o resultado (mantendo a versão original para operações futuras)
faturamento_lojas_dia_styled = faturamento_lojas_dia.style.hide(axis='index')
display(faturamento_lojas_dia_styled)

# Exportar para Excel
nome_arquivo = f'{data_indicador.month}_{data_indicador.day}_Ranking Dia.xlsx'
faturamento_lojas_dia.to_excel(f'Backup Arquivos Lojas\{nome_arquivo}', index=False)

### Passo 7 - Enviar e-mail para diretoria

In [9]:
# Converter 'Valor Final' para numérico, substituindo valores inválidos por NaN
faturamento_lojas_ano['Valor Final'] = pd.to_numeric(faturamento_lojas_ano['Valor Final'], errors='coerce')
faturamento_lojas_dia['Valor Final'] = pd.to_numeric(faturamento_lojas_dia['Valor Final'], errors='coerce')

# Ordenar por 'Valor Final' em ordem decrescente e resetar índices
faturamento_lojas_ano = faturamento_lojas_ano.sort_values(by='Valor Final', ascending=False).reset_index(drop=True)
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by='Valor Final', ascending=False).reset_index(drop=True)

# Criar objeto de e-mail no Outlook
outlook = win32.Dispatch('outlook.application')
mail = outlook.CreateItem(0)

# Definir destinatário e assunto do e-mail
mail.To = base_emails.loc[base_emails['Loja'] == 'Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {data_indicador.day}/{data_indicador.month}'

# Criar o corpo do e-mail com rankings do dia e do ano
mail.Body = f'''
Prezados, Segue Relatório do Ranking Diário e Anual das Lojas:

Melhor loja do Dia: {faturamento_lojas_dia.iloc[0]["Loja"]} - R${faturamento_lojas_dia.iloc[0]["Valor Final"]:,.2f}
Pior loja do Dia: {faturamento_lojas_dia.iloc[-1]["Loja"]} - R${faturamento_lojas_dia.iloc[-1]["Valor Final"]:,.2f}

Melhor loja do Ano: {faturamento_lojas_ano.iloc[0]["Loja"]} - R${faturamento_lojas_ano.iloc[0]["Valor Final"]:,.2f}
Pior loja do Ano: {faturamento_lojas_ano.iloc[-1]["Loja"]} - R${faturamento_lojas_ano.iloc[-1]["Valor Final"]:,.2f}

Segue em anexo os rankings detalhados.

Atenciosamente,
Fernando Vale
'''

# Anexar arquivos com rankings anual e diário
attachment = pathlib.Path.cwd() / caminho_backup / f'{data_indicador.month}_{data_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment = pathlib.Path.cwd() / caminho_backup / f'{data_indicador.month}_{data_indicador.day}_Ranking Dia.xlsx'
mail.Attachments.Add(str(attachment))

# Enviar o e-mail e exibir confirmação
mail.Send()
print('E-mail da Diretoria enviado')

E-mail da Diretoria enviado